# frontend commands

# prefer bash
set shell := ["bash", "-uc"]

# Frontend commands
use_nvm := "export NVM_DIR=\"${NVM_DIR:-$HOME/.nvm}\"; [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"; [ -e ./local-nvm.sh ] && . ./local-nvm.sh; nvm use"

# this help
[default]
help:
    @just --list

# Refresh dependencies locally
refresh:
    {{ use_nvm }} && pnpm install

# Run dev server
dev:
    @echo "Running dev frontend"
    {{ use_nvm }} && pnpm run dev

# ===========================================
# i18n
# ===========================================

# sync translations
[group('i18n')]
i18nsync:
    {{ use_nvm }} && pnpm i18nsync && pnpm prettier --write src/lib/i18n/messages


# ===========================================
# QUALITY
# ===========================================

[group('quality')]
lint:
    {{ use_nvm }} && pnpm format

[group('quality')]
lint-one file:
    {{ use_nvm }} && pnpm prettier --write {{ file }}

# quality checks & tests
[group('quality')]
check: quality_check test

# quality checks
[group('quality')]
quality_check:
    @echo "pnpm check ======================================"
    {{ use_nvm }} && pnpm check
    @echo "pnpm lint ======================================"
    {{ use_nvm }} && pnpm lint
    @echo "pnpm i18ncheck ======================================"
    {{ use_nvm }} && pnpm i18ncheck
    @echo "pnpm build ======================================"
    {{ use_nvm }} && pnpm build

[group('quality')]
test:
    {{ use_nvm }} && pnpm test
